### ISSUE TITLE
chore: Add CORS Origin

### ISSUE THREAD

**Issue by SeokyoungYou** [eakyoungyu/DDobok-backend#1]
![image](https://user-images.githubusercontent.com/79842380/216888546-8cea5d19-b096-4c8e-a17e-6d11bfd60adf.png)

**Comment by eakyoungyu** [comment]
Added ddobok.com in cors origin.
https://github.com/eakyoungyu/DDobok-backend/commit/c80dded6ec69ced90ba413a4c2be7d23fb9fcc00
